name: mypet
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  kakao_flutter_sdk: ^1.9.0

  http: ^1.2.1
  image_picker: ^1.1.2
  fl_chart: ^0.68.0
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"

